{"tag": "function", "depth": 1, "time": 1760534755.7704704, "data": {"name": "connect_device", "call_args": {"uri": "Android://127.0.0.1:5037/H4K0220B25000014", "device": "H4K0220B25000014"}, "start_time": 1760534755.1592772, "ret": "<Android 'H4K0220B25000014'>", "end_time": 1760534755.7704704}}
{"tag": "function", "depth": 1, "time": 1760534756.1471488, "data": {"name": "start_app", "call_args": {"package": "com.tomoviee.ai", "activity": null, "device": "H4K0220B25000014"}, "start_time": 1760534755.770983, "ret": null, "end_time": 1760534756.1471488}}
{"tag": "function", "depth": 3, "time": 1760534757.9745674, "data": {"name": "_cv_match", "call_args": {"screen": "array([[[ 0,  0,  0],\n        [ 0,  0,  0],\n        [ 0,  0,  0],\n        ...,\n        [ 0,  0,  0],\n        [ 0,  0,  0],\n        [ 0,  0,  0]],\n\n       [[ 0,  0,  0],\n        [ 0,  0,  0],\n        [ 0,  0,  0],\n        ...,\n        [ 0,  0,  0],\n        [ 0,  0,  0],\n        [ 0,  0,  0]],\n\n       [[ 0,  0,  0],\n        [ 0,  0,  0],\n        [ 0,  0,  0],\n        ...,\n        [ 0,  0,  0],\n        [ 0,  0,  0],\n        [ 0,  0,  0]],\n\n       ...,\n\n       [[28, 23, 22],\n        [28, 23, 22],\n        [28, 23, 22],\n        ...,\n        [28, 23, 22],\n        [28, 23, 22],\n        [28, 23, 22]],\n\n       [[28, 23, 22],\n        [28, 23, 22],\n        [28, 23, 22],\n        ...,\n        [28, 23, 22],\n        [28, 23, 22],\n        [28, 23, 22]],\n\n       [[28, 23, 22],\n        [28, 23, 22],\n        [28, 23, 22],\n        ...,\n        [28, 23, 22],\n        [28, 23, 22],\n        [28, 23, 22]]], dtype=uint8)"}, "start_time": 1760534757.9725673, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = self._imread()\n                ^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(self.filepath)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1754622220153.png\n", "end_time": 1760534757.9745674}}
{"tag": "function", "depth": 2, "time": 1760534757.9765632, "data": {"name": "loop_find", "call_args": {"query": {"filename": "tpl1754622220153.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": [0.395, -0.969], "resolution": [1240, 2772], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "timeout": 20, "threshold": null, "interval": 0.5, "intervalfunc": null}, "start_time": 1760534756.1481495, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n                ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = self._cv_match(screen)\n                   ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = self._imread()\n                ^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(self.filepath)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1754622220153.png\n", "end_time": 1760534757.9765632}}
{"tag": "function", "depth": 1, "time": 1760534757.9765632, "data": {"name": "touch", "call_args": {"v": {"filename": "tpl1754622220153.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": [0.395, -0.969], "resolution": [1240, 2772], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "kwargs": {}, "times": 1, "device": "H4K0220B25000014"}, "start_time": 1760534756.1481495, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\api.py\", line 366, in touch\n    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n                ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = self._cv_match(screen)\n                   ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = self._imread()\n                ^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(self.filepath)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1754622220153.png\n", "end_time": 1760534757.9765632}}
{"tag": "function", "depth": 2, "time": 1760534758.1106098, "data": {"name": "try_log_screen", "call_args": {"screen": null, "quality": null, "max_size": null}, "start_time": 1760534757.9765632, "ret": {"screen": "1760534758063.jpg", "resolution": [1152, 2376]}, "end_time": 1760534758.1106098}}
{"tag": "info", "depth": 1, "time": 1760534758.1116133, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\cli\\runner.py\", line 72, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"c:\\Users\\ws\\Desktop\\Automation_Platform\\uploads\\test_cases\\test2_Test1.py\", line 12, in <module>\n    touch(Template(r\"tpl1754622220153.png\", record_pos=(0.395, -0.969), resolution=(1240, 2772)))\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\api.py\", line 366, in touch\n    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n                ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = self._cv_match(screen)\n                   ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 139, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = self._imread()\n                ^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(self.filepath)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ws\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1754622220153.png\n"}}
